### ISSUE TITLE
add qpOASES REQUIRED

### ISSUE THREAD

**Issue by ahoarau** [ocra-recipes/ocra-recipes#21]
As qpoases is lightweight and easy to install on osx and linux, I think we should enable it by default in order to avoid those `USE_QPOASES` compile options that both ocra-recipes and wbi should carry.

**Comment by traversaro** [comment]
:+1:

**Comment by rlober** [comment]
Considering that it will probably become the de facto solver for the controller - I agree with this. Quadprog++, being no longer under development, will probably be less an less useful. 

@ahoarau I guess you are for this change so I am going to close this as voted YES.
