### ISSUE TITLE
FullPosture task not working properly

### ISSUE THREAD

**Issue by rlober** [ocra-recipes/ocra-recipes#25]
A full posture task should be sufficient to maintain the robot upright when in floatingBase. Its not very useful but it is a good sanity check. Recent testing with only a full posture task in floating base shows the robot falling over which equals something stinky in the posture task(s)? Need to investigate...

**Comment by rlober** [comment]
So after plotting the ouptu of the controller (without sending the torques to the robot) I get the following plots:

controller torque refs are in red and real torques measured are in blue:

### Full Posture only:

![nooutput_posturetest](https://cloud.githubusercontent.com/assets/3417094/20758858/78c2b770-b71b-11e6-91b1-c3566eec18c0.png)


### wholeBodyTaskSet:

![nooutput_wholebodytaskset](https://cloud.githubusercontent.com/assets/3417094/20758857/787a7b4a-b71b-11e6-9fba-4499c97cef59.png)


### Full posture with feet contacts

![nooutput_posturetest_withcontacts](https://cloud.githubusercontent.com/assets/3417094/20759270/c0236078-b71c-11e6-8eff-499bfcbbe62c.png)

It is clear that in the Full posture only case the refs are all 0. When I add the contacts the refs start to resemble something correct but still aren't right. So something is wrong in the with the posture task.

**Comment by jeljaik** [comment]
On the other hand using the `FixedBaseBasic` (no floating base) tasks set with the postural task only does not present the same problem.

**Comment by rlober** [comment]
Yes I confirm.

**Comment by rlober** [comment]
deprecated - cleanup
