### ISSUE TITLE
Eigen 3.3 Compatibility / Port to KDL or iDynTree?

### ISSUE THREAD

**Issue by rlober** [ocra-recipes/ocra-recipes#26]
# The problem
[Currently ocra will not compile with `eigen3.3`](https://github.com/robotology/codyco-superbuild/pull/156). This is mostly due to the `eigen_lgsm` lib. Maintaining the lgsm lib is going to be a pain - especially since it was written by wizards. 

# Solution...?
The idea is that we will shift *brutally* to a different solid mechanics lib. Our current choices are [`orocos::KDL`](https://github.com/orocos/orocos_kinematics_dynamics) and [`iDynTree`](https://github.com/robotology/idyntree). This issue will be for comparing them based on our needs and tracking the eventual testing/port.

I am counting on the input of you guys for this:
@traversaro, @ahoarau, @jeljaik, @DanielePucci, @iron76, @francesco-romano

Any suggestions/recommendations you may have would be welcome.

# Needs

Here we will try to detail the functionalities desired by the lib.

### Basic solid mechanics math 

Right now LGSM relies on Lie groups and lie algebras for this. I think that practically speaking both `KDL` and `iDynTree` do as well, but without formally treating them as such? 

### Maintainability 

@jeljaik and I will be gone someday so ocra will eventually become some poor future grad student's problem. I don't want them to have the same issue that we are currently having with LGSM. 

### Stability

The lib needs to be mature 'cause I can't be codin' all damn day - gotta do me some science.

### Ease of install and few dependencies 

Would love for the lib to be easy to install with minimal dependencies and everything available through `apt` or `brew` - to hell with Windows! JK, I would like windows compatibility as well. 

More to come...

**Comment by traversaro** [comment]
@rlober Do you believe I never saw this issue? 

Another possibility that I see (possibly the easiest one) is just to stick with Eigen and just have a bunch of simple function to deal with the "Lie group" stuff, such as Adjoint matrices and Inertia Matrices: this is the strategy used by Drake ( https://github.com/RobotLocomotion/drake )  and Dart ( https://github.com/dartsim/dart ).  
I would start with a simple header with a bunch of typedefs such as
~~~
typedef Eigen::Matrix<double, 6, 1> Twistd; 
typedef Eigen::Matrix<double, 6, 1> Wrenchd; 
~~~
or some class inheritance if you use some of the helper methods defined in eigen_lgsm : 
~~~
class Displacementd: public Eigen::Matrix<double, 6, 1> 
{
public:
   getRotation ... 
}
~~~ 

And then implement all the methods/functions that you need (that I don't think are even the 5% of what implemented in eigen_lgsm, based on my quick glance in the code).

**Comment by ahoarau** [comment]
I like the idea of re-writting this library. I thought of a less elegant solution consisting of embedding `eigen 3.2` + `eigen_lgsm` in a `third_party/` directory at the root of the repo (?).

**Comment by jeljaik** [comment]
This week we were gonna implement the "less elegant" solution indeed. Thanks
for the suggestions

**Comment by rlober** [comment]
deprecated - cleanup

**Comment by rlober** [comment]
deprecated - cleanup
