### ISSUE TITLE
Christmas wishlist for OCRA

### ISSUE THREAD

**Issue by rlober** [ocra-recipes/ocra-recipes#3]
Hey @ahoarau @traversaro @DanielePucci @iron76

So I want to put together a list of features for `ocra-recipes` to make it more usable and faster. So this will be sort of a to do/wish list for ocra as it goes into heavier usage (hopefully).
-  [x]  Compiles nicely with clang and osx.
  **_update: (15/02/16)_ @ahoarau finished this up with the `-fPIC` flag.**
-  [x]  Memory efficient and low overhead yarp input/output control ports for the task managers. (@traversaro) I forget the little trick you mentioned to make this feasible. 
  **_update: (03/01/16)_ So my solution to this is currently, is to open a ratethread derived class to update state variables in parallel execution to the controller. So far this works pretty well and has not caused any noticeable decline in controller performance.**
-  [ ]  Better handling of task activation and deactivation.
-  [x]  Move `wOcra`: `TaskManagers`, `Trajectory`, `taskParser` etc. to `ocra` so we can reuse them amongst `wocra`, `gocra` and `hocra`. **_update: (24/02/16)_ Done.**
-  [x]  `hocra` (a.k.a. `hoarocra`) @ahoarau 
-  [x]  `ocra-rtt-plugins` for the KUKA.
-  [ ]  An automated controller benchmark testing system (need to work with @iron76 & @traversaro on [`RTF`](https://github.com/robotology/robot-testing) )
-  [x]  Generated doxygen for comments in ocra-recipes. Properly document [`ocra-wbi-plugins`](https://github.com/ocra-recipes/ocra-wbi-plugins). 
  **_update: (03/01/16)_ this has been more or less accomplished but the output leaves much to be desired and I don't have the .sty files needed for the latex compilation.**
-  [ ]  Video tutorials for using the controller(s). I was thinking of doing some superbuild tutorials to go with them as well @traversaro @DanielePucci. I actually just realized that superbuild compiled `YARP` and `icub-main` if you don't have them! :+1: guys!

I imagine this list will be ever evolving but I think this is a good place to start.

**Comment by traversaro** [comment]
For the OS X compilation part, see https://github.com/ocra-recipes/ocra-recipes/issues/4 .

For how to efficiently send data structure on a YARP port, please see the following tutorials: 
- How to use the `Portable` interface to manually write serialization/deserialization methods for C++ data structures http://www.yarp.it/port_expert.html (Datatypes section in particular)
- How to use IDL (interface definition languages) such as ROS msg or Thrift to generate a data structure that can be sent/received on a port: Thrift: http://www.yarp.it/thrift_tutorial_portable.html ROS: http://www.yarp.it/rostypes_tutorial_portable.html

**Comment by rlober** [comment]
Thanks @traversaro I am going to discuss the cmake revamp with @ahoarau when we get back next week.

**Comment by ahoarau** [comment]
- [ ] Custom prints : OCRA_INFO() , OCRA_ERROR(), OCRA_WARNING(), OCRA_DEBUG()

**Comment by rlober** [comment]
@ahoarau I am down with this. Maybe since we have integrated yarp fairly thoroughly into the code base if we could just inherit from `yarp::os::Log` and `yarp::os::LogStream`

**Comment by rlober** [comment]
Closing this issue, and migrating to #16
