### ISSUE TITLE
Add uninstall target 

### ISSUE THREAD

**Issue by traversaro** [ocra-recipes/ocra-recipes#5]
It is sometimes convenient to have an `uninstall` target. It can be easily added with this cmake macro: https://github.com/robotology/ycm/blob/master/modules/AddUninstallTarget.cmake .

**Comment by rlober** [comment]
@ahoarau for this one.

**Comment by rlober** [comment]
Looks like @ahoarau closed this in: 6bee35defdc8a5152a68041f937d65475128114e
