### ISSUE TITLE
Follow rule of 3.

### ISSUE THREAD

**Issue by rlober** [ocra-recipes/ocra-recipes#6]
We need to go through the code base and make sure we have properly overloaded the assignment operator, copy constructors and destructors for all our classes. I am mostly referring to `wocra` but it wouldn't surprise me if these we overlooked in both `ocra` and `gocra`. My main concern is the way we implement a task manager dictionary within the task sequences.

**Comment by rlober** [comment]
Considering that we will be converting to C++11 soon, we will close this for now and just take these rules into consideration as we go through an update the classes.

**Comment by traversaro** [comment]
Notice that in C++11 the rule of 3 becomes the rule of 5!

**Comment by rlober** [comment]
Haha damn you `move`!
