### ISSUE TITLE
Does not compile on Xcode

### ISSUE THREAD

**Issue by ahoarau** [ocra-recipes/ocra-recipes#8]
https://travis-ci.org/ocra-recipes/ocra-wbi-plugins/jobs/109352106
@traversaro Any ideas ?

**Comment by traversaro** [comment]
@ahoarau I compiled it now and it works fine.. fixed by https://github.com/ocra-recipes/ocra-recipes/commit/76e0b384058cbc609ae7d387e8643cdc2b32eba5 ?

**Comment by ahoarau** [comment]
yep :+1:  !
